# Configuración común a todos los entornos (dev, prod, Docker)
spring.application.name=FFE
spring.profiles.default=dev

application.title=${APPLICATION_TITLE:Aplicacion de Venta de entradas de Cine con Spring Boot}
application.version=${APPLICATION_VERSION:1.0.0}

server.port=${PORT:3010}
server.servlet.session.tracking-modes=cookie
api.version=${API_VERSION:v1}

## Pebble
pebble.suffix=.peb.html
pebble.cache=false
pebble.charset=UTF-8

## Subida de carátulas
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
